version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    # Variables NO sensibles aquí; lo sensible va en Dokploy → Environment
    environment:
      NODE_ENV: production
      PORT: 3000
      # CORS (dominios del front)
      FRONTEND_URL: https://rtakabinetssolutions.com
      FRONTEND_URL_WWW: https://www.rtakabinetssolutions.com

    restart: unless-stopped
    networks:
      - shared_net
      - dokploy-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
       
        VITE_API_URL: "https://api.rtakabinetssolutions.com"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - shared_net
      - dokploy-network

networks:
  shared_net:
    external: true          
  dokploy-network:
    external: true          