version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: https://rtakabinetssolutions.com
      FRONTEND_URL_WWW: https://www.rtakabinetssolutions.com
      DB_HOST: custom-carpentry-alex-customcarpentry-zsw4oq
      DB_PORT: 3306
      DB_NAME: customcarpent
      DB_USER: root
      DB_PASS: Pa12724110$
      JWT_SECRET: 1234abcd5678efgh
      DB_ADDRESS_FAMILY: "4"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: "https://api.rtakabinetssolutions.com"
    environment:
      NODE_ENV: production
    restart: unless-stopped
