# Dockerfile.frontend

# 1) Build de Vite
FROM node:18-bullseye AS builder
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
COPY ./frontend ./
RUN npm run build

# 2) Nginx para servir la SPA
FROM nginx:1.27-alpine
# Copiamos nuestra configuración personalizada
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
# Copiamos el build de Vite
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]