# Dockerfile.frontend
FROM node:18-bullseye AS builder
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
COPY ./frontend ./
RUN npm run build

FROM nginx:alpine
# (Opcional SPA) nginx.conf con try_files si usas react-router
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]