# Usar Node 18 (compatible con Vite)
FROM node:18-bullseye AS builder

WORKDIR /app

COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend ./

# Construir la app
RUN npm run build

# Servir con Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]