services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: customcarpent
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:5000"
    depends_on:
      - db
    environment:  # <-- agrega esto
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: customcarpent
      DB_PORT: 3306
      EMAIL_USER: alexholguinmartinez22@gmail.com
      EMAIL_PASS: ehyxjvvhlpmqjctg
      EMAIL_RECEIVER: Carpentry.ido@gmail.com
      JWT_SECRET: 1234abcd5678efgh
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: