version: "3.9"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Fuerza redirección a HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=Carpentry.ido@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: https://rtakabinetsolutions.com
      FRONTEND_URL_WWW: https://www.rtakabinetsolutions.com
      DB_HOST: custom-carpentry-alex-customcarpentry-zsw4oq
      DB_PORT: 3306
      DB_NAME: customcarpent
      DB_USER: root
      DB_PASS: Pa12724110$
      DB_ADDRESS_FAMILY: "4"
      JWT_SECRET: 1234abcd5678efgh
      CORS_ORIGIN: https://rtakabinetsolutions.com,https://www.rtakabinetsolutions.com,https://rtakabinetssolutions.com,https://www.rtakabinetssolutions.com
    restart: unless-stopped
    labels:
      # Redirect dominio viejo -> nuevo
      - "traefik.http.middlewares.redirect-rta.redirectregex.regex=^https?://(www\\.)?rtakabinetssolutions\\.com(.*)"
      - "traefik.http.middlewares.redirect-rta.redirectregex.replacement=https://rtakabinetsolutions.com$2"
      - "traefik.http.middlewares.redirect-rta.redirectregex.permanent=true"

      - "traefik.http.routers.redirect-rta.rule=Host(`rtakabinetssolutions.com`,`www.rtakabinetssolutions.com`)"
      - "traefik.http.routers.redirect-rta.entrypoints=web,websecure"
      - "traefik.http.routers.redirect-rta.tls=true"
      - "traefik.http.routers.redirect-rta.service=noop@internal"
      - "traefik.http.routers.redirect-rta.middlewares=redirect-rta"
      - "traefik.http.routers.redirect-rta.priority=1000"

      # Router backend
      - "traefik.http.routers.backend.rule=Host(`api.rtakabinetsolutions.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: "https://api.rtakabinetsolutions.com"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    labels:
      # Router frontend
      - "traefik.http.routers.frontend.rule=Host(`rtakabinetsolutions.com`,`www.rtakabinetsolutions.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

networks:
  default:
    name: rtakabinetsolutions_net